<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Radioamatérská Volací Značka</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Vyhledat Zemi podle Radioamatérské Volací Značky</h1>
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <div class="form-group">
                <label for="callsign">Zadejte volací značku nebo jen PREFIX:</label>
                <input type="text" class="form-control" id="callsign" name="callsign" required>
            </div>
            <button type="submit" class="btn btn-primary" name="submit">Look</button>
        </form>
        <?php
        if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['submit'])) {
            // Funkce pro získání země podle prefixu
            function lookupCountry($prefix) {
                // Databáze s předem danými prefixy a zeměmi
                $countries = array(
                    "OK" => "Czech Republic",
                    "2A" => "United Kingdom of Great Britain and Northern Ireland",
                    "2B" => "United Kingdom of Great Britain and Northern Ireland",
                    "2C" => "United Kingdom of Great Britain and Northern Ireland",
                    "2D" => "United Kingdom of Great Britain and Northern Ireland",
                    "2E" => "United Kingdom of Great Britain and Northern Ireland",
                    "2F" => "United Kingdom of Great Britain and Northern Ireland",
                    "2G" => "United Kingdom of Great Britain and Northern Ireland",
                    "2H" => "United Kingdom of Great Britain and Northern Ireland",
                    "2I" => "United Kingdom of Great Britain and Northern Ireland",
                    "2J" => "United Kingdom of Great Britain and Northern Ireland",
                    "2K" => "United Kingdom of Great Britain and Northern Ireland",
                    "2L" => "United Kingdom of Great Britain and Northern Ireland",
                    "2M" => "United Kingdom of Great Britain and Northern Ireland",
                    "2N" => "United Kingdom of Great Britain and Northern Ireland",
                    "2O" => "United Kingdom of Great Britain and Northern Ireland",
                    "2P" => "United Kingdom of Great Britain and Northern Ireland",
                    "2Q" => "United Kingdom of Great Britain and Northern Ireland",
                    "2R" => "United Kingdom of Great Britain and Northern Ireland",
                    "2T" => "United Kingdom of Great Britain and Northern Ireland",
                    "2U" => "United Kingdom of Great Britain and Northern Ireland",
                    "2V" => "United Kingdom of Great Britain and Northern Ireland",
                    "2W" => "United Kingdom of Great Britain and Northern Ireland",
                    "2X" => "United Kingdom of Great Britain and Northern Ireland",
                    "2Y" => "United Kingdom of Great Britain and Northern Ireland",
                    "2Z" => "United Kingdom of Great Britain and Northern Ireland",
                    "3A" => "Monaco",
                    "3B" => "Mauritius",
                    "3C" => "Equatorial Guinea",
                    "3D" => "Swaziland",
                    "3E" => "Panama",
                    "3F" => "Panama",
                    "3G" => "Chile",
                    "3H" => "China",
                    "3I" => "China",
                    "3J" => "China",
                    "3K" => "China",
                    "3L" => "China",
                    "3M" => "China",
                    "3N" => "China",
                    "3O" => "China",
                    "3P" => "China",
                    "3Q" => "China",
                    "3R" => "China",
                    "3S" => "China",
                    "3T" => "China",
                    "3U" => "China",
                    "3V" => "Tunisia",
                    "3W" => "Viet Nam",
                    "3X" => "Guinea",
                    "3Y" => "Norway",
                    "3Z" => "Polan",
                    "4A" => "Mexico",
                    "4B" => "Mexico",
                    "4C" => "Mexico",
                    "4D" => "Philippines",
                    "4E" => "Philippines",
                    "4F" => "Philippines",
                    "4G" => "Philippines",
                    "4H" => "Philippines",
                    "4I" => "Philippines",
                    "4J" => "Azerbaijani Republic",
                    "4K" => "Azerbaijani Republic",
                    "4K" => "Azerbaijani Republic",
                    "4L" => "Georgia",
                    "4M" => "Venezuela",
                    "4O" => "Montenegro",
                    "4P" => "Sri Lanka",
                    "4Q" => "Sri Lanka",
                    "4R" => "Sri Lanka",
                    "4S" => "Sri Lanka",
                    "4T" => "Peru",
                    "4U" => "United Nation",
                    "4V" => "Haity",
                    "4W" => "Timor-Leste",
                    "4X" => "Israel",
                    "4Y" => "International Civil Aviation Organization",
                    "4Z" => "Israel",
                    "5A" => "Socialist People's Libyan Arab Jamahiriya",
                    "5B" => "Cyprus",
                    "5C" => "Morocco",
                    "5D" => "Morocco",
                    "5E" => "Morocco",
                    "5F" => "Morocco",
                    "5G" => "Morocco",
                    "5H" => "Tanzania",
                    "5J" => "Columbia",
                    "5K" => "Columbia",
                    "5L" => "Liberia",
                    "5M" => "Liberia",
                    "5N" => "Nigeria",
                    "5O" => "Nigeria",
                    "5P" => "Denmark",
                    "5Q" => "Denmark",
                    "5S" => "Madagaskar",
                    "5T" => "Mauritania (Islamic Republic of)",
                    "5U" => "Niger",
                    "5V" => "Togolese",
                    "5W" => "Samoa",
                    "5X" => "Uganda",
                    "5Y" => "Kenya",
                    "5Z" => "Kenya",
                    "6A" => "Egypt",
                    "6B" => "Egypt",
                    "6C" => "Syrian Arab Republic",
                    "6D" => "Mexico",
                    "6E" => "Mexico",
                    "6F" => "Mexico",
                    "6G" => "Mexico",
                    "6H" => "Mexico",
                    "6I" => "Mexico",
                    "6J" => "Mexico",
                    "6K" => "Korea",
                    "6L" => "Korea",
                    "6M" => "Korea",
                    "6N" => "Korea",
                    "6O" => "Somali Democratic Republic",
                    "6P" => "Pakistan",
                    "6Q" => "Pakistan",
                    "6R" => "Pakistan",
                    "6S" => "Pakistan",
                    "6T" => "Sudan",
                    "6U" => "Sudan",
                    "6V" => "Senegal",
                    "6W" => "Senegal",
                    "6X" => "Madagaskar",
                    "6Y" => "Jamaica",
                    "6Z" => "Liberia",
                    "7A" => "Indonesia",
                    "7B" => "Indonesia",
                    "7C" => "Indonesia",
                    "7D" => "Indonesia",
                    "7E" => "Indonesia",
                    "7F" => "Indonesia",
                    "7G" => "Indonesia",
                    "7H" => "Indonesia",
                    "7I" => "Indonesia",
                    "7J" => "Japan",
                    "7K" => "Japan",
                    "7L" => "Japan",
                    "7M" => "Japan",
                    "7N" => "Japan",
                    "7O" => "Yemen",
                    "7P" => "Lesotho",
                    "7Q" => "Malawi",
                    "7R" => "Algeria",
                    "7S" => "Sweden",
                    "7T" => "Algeria",
                    "7U" => "Algeria",
                    "7V" => "Algeria",
                    "7W" => "Algeria",
                    "7X" => "Algeria",
                    "7Y" => "Algeria",
                    "7Z" => "Saudi Arabia",
                    "8A" => "Indonesia",
                    "8B" => "Indonesia",
                    "8C" => "Indonesia",
                    "8D" => "Indonesia",
                    "8E" => "Indonesia",
                    "8F" => "Indonesia",
                    "8G" => "Indonesia",
                    "8H" => "Indonesia",
                    "8I" => "Indonesia",
                    "8J" => "Japan",
                    "8K" => "Japan",
                    "8L" => "Japan",
                    "8M" => "Japan",
                    "8N" => "Japan",
                    "8O" => "Botswana",
                    "8P" => "Barbados",
                    "8Q" => "Maledives",
                    "8R" => "Guyana",
                    "8S" => "Sweden",
                    "8T" => "India",
                    "8U" => "India",
                    "8V" => "India",
                    "8W" => "India",
                    "8X" => "India",
                    "8Y" => "India",
                    "8Z" => "Saudi Arabia",
                    "9A" => "Croatia",
                    "9B" => "Iran",
                    "9C" => "Iran",
                    "9D" => "Iran",
                    "9E" => "Ethiopia",
                    "9F" => "Ethiopia",
                    "9G" => "Ghana",
                    "9H" => "Malta",
                    "9I" => "Zambia",
                    "9J" => "Iran",
                    "9K" => "Kuwait",
                    "9L" => "Sierra Leone",
                    "9M" => "Malaysia",
                    "9N" => "Nepal",
                    "9O" => "Congo",
                    "9P" => "Congo",
                    "9Q" => "Congo",
                    "9R" => "Congo",
                    "9S" => "Congo",
                    "9T" => "Congo",
                    "9U" => "Burundy",
                    "9V" => "Singapore",
                    "9W" => "Malaysia",
                    "9X" => "Rwanda",
                    "9Y" => "Trinidad, Tobago",
                    "A2" => "Botswana",
                    "A3" => "Tonga",
                    "A4" => "Oman",
                    "A5" => "Bhutan",
                    "A6" => "United Arab Emirates",
                    "A7" => "Qatar",
                    "A8" => "Liberia",
                    "A9" => "Bahrain",
                    "AA" => "USA",
                    "AB" => "USA",
                    "AC" => "USA",
                    "AD" => "USA",
                    "AE" => "USA",
                    "AF" => "USA",
                    "AG" => "USA",
                    "AH" => "USA",
                    "AI" => "USA",
                    "AJ" => "USA",
                    "AK" => "USA",
                    "AL" => "USA",
                    "AM" => "Spain",
                    "AN" => "Spain",
                    "AM" => "Spain",
                    "AO" => "Spain",
                    "AP" => "Pakistan",
                    "AQ" => "Pakistan",
                    "AR" => "Pakistan",
                    "AS" => "Pakistan",
                    "AT" => "India",
                    "AU" => "India",
                    "AV" => "India",
                    "AW" => "India",
                    "AX" => "Australia",
                    "AY" => "Argentina",
                    "AZ" => "Argentina",
                    "BA" => "China",
                    "BB" => "China",
                    "BC" => "China",
                    "BD" => "China",
                    "BE" => "China",
                    "BF" => "China",
                    "BG" => "China",
                    "BH" => "China",
                    "BI" => "China",
                    "BJ" => "China",
                    "BK" => "China",
                    "BL" => "China",
                    "BM" => "China",
                    "BN" => "China",
                    "BO" => "China",
                    "BP" => "China",
                    "BQ" => "China",
                    "BR" => "China",
                    "BS" => "China",
                    "BT" => "China",
                    "BU" => "China",
                    "BV" => "China",
                    "BW" => "China",
                    "BX" => "China",
                    "BY" => "China",
                    "BZ" => "China",
                    "C2" => "Naru",
                    "C3" => "Andora",
                    "C4" => "Cyprus",
                    "C5" => "Gambia",
                    "C6" => "Bahamas",
                    "C7" => "World Meterorological Org.",
                    "C8" => "Mozambique",
                    "C9" => "Mozambiqe",
                    "CA" => "Chile",
                    "CB" => "Chile",
                    "CC" => "Chile",
                    "CD" => "Chile",
                    "CE" => "Chile",
                    "CF" => "Canada",
                    "CG" => "Canada",
                    "CH" => "Canada",
                    "CI" => "Canada",
                    "CJ" => "Canada",
                    "CK" => "Canada",
                    "CL" => "Cuba",
                    "CP" => "Bolivia",
                    "CQ" => "Portugal",
                    "CR" => "Portugal",
                    "CT" => "Portugal",
                    "CS" => "Portugal",
                    "CU" => "Portugal",
                    "CV" => "Uruguay",
                    "CW" => "Uruguay",
                    "CX" => "Uruguay",
                    "CY" => "Canada",
                    "CZ" => "Canada",
                    


                    






                    

                    
                );

                // Kontrola DB
                if (array_key_exists($prefix, $countries)) {
                    return $countries[$prefix];
                } else {
                    return "Země nenalezena pro tento prefix.";
                }
            }

            $callsign = strtoupper($_POST["callsign"]); // Převede volací značku na velká písmena
            $prefix = substr($callsign, 0, 2); // Získá prefix z volací značky

            // Zavolání funkce pro vyhledání země podle prefixu
            $country = lookupCountry($prefix);

            // Výstup
            echo "<div class='mt-4'>";
            echo "<h2>Informace o volací značce $callsign:</h2>";
            echo "<p><strong>Prefix:</strong> $prefix</p>";
            echo "<p><strong>Země:</strong> $country</p>";
            echo "</div>";
        }
        ?>
    </div>
</body>
</html>
